batch_num: 1000
length: 583
base_prob_weight: 0.4


device: "cuda"
# device: "cpu"
seed: 0
train_bs: 128

eval_step: 100
eval_bs: 64
lr: 0.001
train_alpha: 1
max_threads: 64
# sample_temperature: 1

cai_table_path: ./codon_usage_freq_table_human.csv
save_path: ./save/random_data
pretrain_weights: 
train_data_path:
  - ./data/train_dataset.csv

eval_data_path:
  - ./data/test_dataset.csv

embedder:
  model_dir: "/data/jqhuang/workspace/rna_optimize/CodonBERT/pretrain_weights"
  # max_length: 1022
  embedding_size: 768

actor:
  # lstm:
  #   hidden_size: 64
  #   num_layers: 1
  # transformer:
  #   num_layers: 1
  #   nhead: 1
  hidden_size: 256
  context_size: 256
critic:
  # glimpse_size: 128
  hidden_size: 256
